name: broncomoredirect_app
description: Make BroncoDirect more direct

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  http: ^0.13.4
  path_provider: ^2.0.5
  json_annotation: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.4
  json_serializable: ^5.0.2

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/bmd_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/degree_requirements/
